### ISSUE TITLE
mkArchive.sh

### ISSUE THREAD

**Issue by Stokykyle** [kreezxil/Technic-Solder-Support#1]
I'm currently getting an error saying mv: cannot stat '/var/www/Repo/temp/*': No such file or directory

**Comment by kreezxil** [comment]
Make sure that path exists. You can use

mkdir -p /var/www/Repo/temp

The -p option tells Linux to make ask the missing directories in that path.

Also you didn't tell me how long you've been using my script so I don't
have a clue as to if this is a setup problem, or an EBKAC issue, or
something else.

**Comment by kreezxil** [comment]
Also did you read my description on github, as it does say there is a problem with the script and that I need your help in fixing it.

I also build all my packs inside the twitch app as it is less work for me when it comes to maintaining a pack.

**Comment by kreezxil** [comment]
The only reason to use technic solder is incremental update when a modpack changes a few mods and to thwart licensing hassles. The latter is disrespectful of mod author's desire for their hard work.
